# fly.toml app configuration file generated for gemini-proxy on 2023-12-14T13:23:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gemini-proxy"
primary_region = "iad"

[build]

[env]
  PORT = "8000"

[processes]
  app = "run --allow-net ./main.ts"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
